### ISSUE TITLE
Change date_created and date_updated to timestamps in website-cms

### ISSUE THREAD

**Issue by paulrudy** [directus-labs/directus-templates#4]
Most of the date_created and date_updated fields in the website-cms template are of type Timestamp, but a few are of type Datetime: Posts and Pages if memory serves. Since these fields have relative time selected, the Datetime presents a problem where if creating a post from a region that is not UTC, the relative date appears to be in the future or past.

My suggestion would be to change these fields to be of type Timestamp instead. With that change, relative dates work with the user's local time.

**Comment by bryantgillespie** [comment]
The website-cms will be deprecated soon in favor of our Simple Website CMS template.
https://directus.io/templates/simple-cms
